#define CURR_VNUM "CURR_VNUM"
#define MAX_VNUM_LEN 1024
#define SDIR_XATTR "SDIR_XATTR"
#define NUM_CHANGES_XATTR "NUM_CHANGES"
#define SDIR_FILETYPE "SDIR"
#define DIR_PERMS 0755 | S_IFDIR
#define REG_PERMS 0755 | S_IFREG
#define MAX_NO_CHANGES 50